name: stac-env

channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - dask 
  - earthengine-api
  - folium
  - geopandas
  - jupyter
  - matplotlib
  - pandas
  - pystac=1.8
  - pyproj
  - python=3.10
  - pytorch=2.0.1
  - pytorch-cuda=11.7
  - pydantic=1.9.2
  - rasterio
  - rasterstats
  - richdem
  - rio-cogeo
  - scikit-image
  - scikit-learn
  - scipy
  - seaborn
  - shapely
  - sphinx
  - torchvision=0.15.2
  - torchmetrics 
  - tqdm
  - pysheds
  - pip
  - pip:
      - geetools
      - python-dotenv>=0.5.1
      - torchgeo
      - wget
      - git+https://github.com/Ecotrust/gdstools@v0.1
      - -e . # change . to the desired local package path
