labels:
  BLM-COOS:
    provider_name: Bureau of Land Management
    provider_url: 
    provider_roles: [licensor, producer, processor, host]
    description: > 
      The study area encompasses approximately 250,000 acres of land, comprising a combination of the USDI Bureau of Land Management (BLM) 
      and Coquille tribal forests located within the southern coastal forests of Oregon. This region is part of a larger 1.6 million-acre 
      expanse where LIDAR data was systematically gathered. The LIDAR data acquisition was facilitated through 
      the Oregon LIDAR Consortium, focusing on the Oregon South Coast region and spanning from April 2008 to April 2009. LIDAR was acquired at 
      an average of 8 pulses per square meter. The primary objectives of collecting this data were twofold: first, to generate comprehensive 
      and high-resolution models of the bare ground surface; second, to provide point data that could accurately characterize the density 
      and spatial distribution of forest vegetation across the entire surveyed area.

      Tree measurements were conducted on a total of 899 plots, representing 6 tree height classes, within the study area during the years 
      2010 and 2011. To ensure a representative and unbiased sample, a specific spatial constraint was imposed: no two plots, regardless of 
      their origin, could be located within two neighboring cells of one another.
    label_type: vector
    label_properties: [aboveground_biomass]
    label_description: 
    label_task: regression
    label_name: BLM Forest Operations Inventory Vegetation
    label_license: 
      type:
      url: 

  BLM-LANE:
    provider_name: Bureau of Land Management
    provider_url: 
    provider_roles: [licensor, producer, processor, host]
    description: > 
      The Northwest Oregon Bureau of Land Management (BLM) District engaged Hamer Environmental (Hamer) to create 240 field correlation 
      plots in the Fall of 2017. These plots were intended for use in completing a comprehensive stand-level inventory based on LiDAR 
      data collected within the Northwest Oregon BLM District, specifically in Lane County.

      The tree data were measured for both small (11.77-foot radius) and large (41.6-foot radius) plots. Smaller plots, a subset of larger plots, 
      were utilized to quantify smaller trees with a diameter at breast height (DBH) less than 5.5 inches. Larger plots included detailed tree 
      measurements, such as species identification, DBH, total height, crown ratio, height to the base of the live crown, indications of tree 
      lean or a broken top, distance from the plot center, and azimuth from the plot center for all trees present. Large plots also involved 
      measurements of downed woody debris, including details on small and large end diameters, length, and decay class. Additionally, 
      structural characteristics relevant to northern spotted owl habitat were documented for each of the 240 field correlation plots.

      The data collection process was carried out between October 6, 2017, and February 1, 2018.
    label_type: vector
    label_properties: [aboveground_biomass]
    label_description: 
    label_task: regression
    label_name: BLM Forest Operations Inventory Vegetation
    label_license: 
      type:
      url: 

  BLM-ROGUE:
    provider_name: Bureau of Land Management
    provider_url: 
    provider_roles: [licensor, producer, processor, host]
    description: > 
      The study area encompasses around 650,000 acres of land, comprising USDI Bureau of Land Management (BLM) and Oregon Department 
      of Forestry (ODF) forests located in the southern Oregon Cascades. This area is part of a larger 1.4 million-acre region over 
      which LIDAR data was collected in 2012. 

      In the fall of 2013, tree measurements were collected on 240 plots across the study area, representing six tree height classes. 
      The plot protocol employed a nested set of circular, fixed area plots to characterize all trees with a diameter at breast height (DBH) 
      larger than 1 inch. The measurements taken for live and dead trees with a DBH greater than or equal to 6.5 inches included tree number, 
      species, DBH, height, crown base height, and crown ratio. Additionally, within the tree plot, a smaller 1/100-acre plot was nested 
      to collect information for saplings with a DBH less than 6.5 inches.
    label_type: vector
    label_properties: [aboveground_biomass]
    label_description: 
    label_task: regression
    label_name: BLM Forest Operations Inventory Vegetation
    label_license: 
      type:
      url: 

  WA-DNR: 
    provider_name: Washington Department of Natural Resources
    provider_url: https://gis.dnr.wa.gov/site2/rest/services/Public_Forest_Mgmt/WADNR_PUBLIC_RS_FRIS/MapServer
    provider_roles: [licensor, producer, processor, host]
    description: > 
      RS-FRIS is a remote-sensing based forest inventory for WA DNR State Trust lands. RS-FRIS predicts forest 
      conditions using statistical models that relate field measurements to three-dimensional remotely-sensed data 
      (PhoDAR and LiDAR point clouds). Forest metrics are predicted at a scale of 1/10th acre and stored as rasters. 
      The attributes of each RIU are calculated as the mean of the raster cell values that fall within each polygon. 
      Note: origin year and age are exceptions, and are based on the median value.The attributes represent forest 
      conditions as of mid-2017. Origin year and age are periodically updated to reflect harvest activities; all 
      other attributes continue to report mid-2017 conditions.
    label_description: Predicted above ground live biomass. Units = metric tons / acre. 1 metric ton = 1000 kg.
    label_type: vector
    label_properties: [aboveground_biomass]
    label_task: regression
    label_name: WA DNR Remotely Sensed Forest Resource Inventory (RS-FRIS) 
    label_license: 
      type: propietary
      url: 
    # collection: RS_FRIS

  USFS-BLUE-MOUNTAINS: 
    provider_name: US Forest Service
    provider_url: ''
    provider_roles: [licensor, producer, processor, host]
    description: ''
    label_description: ''
    label_type: vector
    label_properties: [aboveground_biomass]
    label_task: regression
    label_name: '' 
    label_license: 
      type: propietary
      url: 
    # collection: RS_FRIS

  USFS-FREMONT-WINEMA: 
    provider_name: US Forest Service
    provider_url: ''
    provider_roles: [licensor, producer, processor, host]
    description: ''
    label_description: ''
    label_type: vector
    label_properties: [aboveground_biomass]
    label_task: regression
    label_name: '' 
    label_license: 
      type: propietary
      url: 
    # collection: RS_FRIS

  USFS-GIFFORD-PINCHOT: 
    provider_name: US Forest Service
    provider_url: ''
    provider_roles: [licensor, producer, processor, host]
    description: ''
    label_description: ''
    label_type: vector
    label_properties: [aboveground_biomass]
    label_task: regression
    label_name: '' 
    label_license: 
      type: propietary
      url: 
    # collection: RS_FRIS

  USFS-MOUNT-BAKER-SNOQUALMIE:
    provider_name: US Forest Service
    provider_url: ''
    provider_roles: [licensor, producer, processor, host]
    description: ''
    label_description: ''
    label_type: vector
    label_properties: [aboveground_biomass]
    label_task: regression
    label_name: '' 
    label_license: 
      type: propietary
      url: 
    # collection: RS_FRIS

  USFS-ROGUE:
    provider_name: US Forest Service
    provider_url: ''
    provider_roles: [licensor, producer, processor, host]
    description: ''
    label_description: ''
    label_type: vector
    label_properties: [aboveground_biomass]
    label_task: regression
    label_name: '' 
    label_license: 
      type: propietary
      url: 
    # collection: RS_FRIS

  USFS-UMPQUA:
    provider_name: US Forest Service
    provider_url: ''
    provider_roles: [licensor, producer, processor, host]
    description: ''
    label_description: ''
    label_type: vector
    label_properties: [aboveground_biomass]
    label_task: regression
    label_name: '' 
    label_license: 
      type: propietary
      url: 
    # collection: RS_FRIS

  USFS-WENATCHEE:
    provider_name: US Forest Service
    provider_url: ''
    provider_roles: [licensor, producer, processor, host]
    description: ''
    label_description: ''
    label_type: vector
    label_properties: [aboveground_biomass]
    label_task: regression
    label_name: '' 
    label_license: 
      type: propietary
      url: 
    # collection: RS_FRIS

items:
  3dep:
    description: > 
      The USGS 3D Elevation Program (3DEP) Bare Earth DEM Dynamic service is based on multi-resolution USGS DEM 
      sources and provides dynamic functions for visualization. These functions include: Hillshade, Aspect Map, 
      Hillshade Stretched, Multi-directional Hillshade, Slope Map, Elevation Tinted Hillshade, Contour. In addition 
      the OGC Web Map Service (WMS) and Web Coverage Service (WCS) interfaces are enabled. Data available in this 
      map service reflects all 3DEP DEM data published as of May 15, 2023.
    providers:
      USGS:
        name: USGS 3D Elevation Program (3DEP)
        type: [licensor, producer, processor, host]
        api: https://elevation.nationalmap.gov/arcgis/rest/services/3DEPElevation/ImageServer/exportImage
        url: https://www.usgs.gov/3d-elevation-program
        # collection: WA_NAIP_2021_9586
    license: 
      type: propietary
      url: https://www.usgs.gov/information-policies-and-instructions/copyrights-and-credits

  gflandsat:
    description: > 
      The Gap Filled Landsat (GFL) product is a 30m resolution, cloud-free, annual composite of Landsat 5, 7, and 8
      surface reflectance data. The GFL product is generated using the Google Earth Engine (GEE) platform and is
      available as a public GEE catalog. The GFL product is described in Kennedy et al. (2019). 
    providers:
      Google:
        name: Google Earth Engine
        roles: [host]
        api: https://earthengine-highvolume.googleapis.com
        url: https://developers.google.com/earth-engine/tutorials/community/histarfm-cloud-and-gap-free-landsat
        # collection: projects/KalmanGFwork/GFLandsat_V1
    license: 
      type: various
      url:

  landtrendr:
    description: >
        LandTrendr is a time series processing algorithm designed to detect and characterize temporal trajectories
        in Landsat pixel stacks. It is a linear spectral mixture model that uses a Kalman filter to identify
        abrupt and gradual changes in spectral trajectories. The algorithm is designed to be scalable and
        applicable to large time series stacks. It is implemented in Google Earth Engine (GEE) and is available
        as a public GEE application. The algorithm is described in Kennedy et al. (2010) and Kennedy et al. (2012).
        The GEE implementation is described in Kennedy et al. (2018).
    providers:
      Google:
        name: Google Earth Engine
        roles: [host]
        api: https://earthengine.googleapis.com
        url: https://emapr.github.io/LT-GEE/introduction.html
        # collection: projects/USFS/LT-GEE
    license: 
      type: various
      url:

  naip:
    description: > 
      The National Agriculture Imagery Program (NAIP), administered by the USDA's Farm Service Agency (FSA), acquires 
      aerial imagery during the agricultural growing seasons in the continental U.S. The NAIP provides 1-meter or better 
      resolution in an orthorectified format. 

      This collection contains NAIP imagery for Oregon and Washington available as 7.5-minute quarter quadrangle, 4-band 
      (RGBN) COG GeoTIFFs. 
    providers:
      Google:
        name: Google Earth Engine
        roles: [host] 
        api: https://earthengine-highvolume.googleapis.com
        url: https://developers.google.com/earth-engine/datasets/catalog/USDA_NAIP_DOQQ 
        # collection: USDA/NAIP/DOQQ
      NOAA:
        name: NOAA Digital Coast
        roles: [host]
        api: 
        url: https://coast.noaa.gov/htdata/raster5/imagery/WA_NAIP_2021_9586/
        # collection: WA_NAIP_2021_9586
      USDA:
        name: USDA Farm Production and Conservation - Business Center, Geospatial Enterprise Operations
        roles: [licensor, producer]
        url: https://naip-usdaonline.hub.arcgis.com/
    license: 
      type: propietary
      url: https://developers.google.com/earth-engine/datasets/catalog/USDA_NAIP_DOQQ#terms-of-use

  landsat8:
    description:
    providers:
      Google:
        name: Google Earth Engine
        roles: [host]
        api: https://earthengine.googleapis.com
        url: https://developers.google.com/earth-engine/datasets/catalog/LANDSAT/LC08/C02/T1_L2
        # collection: LANDSAT/LC08/C01/T1_SR
        USGS:
          name: USGS Earth Explorer
          roles: [licensor, producer]
          url: https://earthexplorer.usgs.gov/
    license:
      type: propietary
      url: https://developers.google.com/earth-engine/datasets/catalog/LANDSAT_LC08_C02_T1_L2#terms-of-use

  lidar:
    description: > 
      Lidar plots. 
    providers:
      Google:
        name: Testing lidar plots
        roles: [host]
        api: ''
        url: ''
        # collection: projects/KalmanGFwork/GFLandsat_V1
    license: 
      type: various
      url:
# {"href": "https://developers.google.com/earth-engine/datasets/catalog/USDA_NAIP_DOQQ#terms-of-use", "rel": "license", "type": "text/html"}